# Generated by Django 6.0.5 on 2026-06-05 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/', verbose_name='CV joint (optionnel)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée par le candidat')], default='pending', max_length=15, verbose_name='Statut')),
                ('recruiter_note', models.TextField(blank=True, verbose_name='Note interne recruteur')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-applied_at'],
            },
        ),
    ]
