# Generated by Django 6.0.5 on 2026-06-05 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer', verbose_name="Offre d'emploi"),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job_offer')},
        ),
    ]
