# Generated by Django 6.0.5 on 2026-06-05 23:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du poste')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('requirements', models.TextField(blank=True, verbose_name='Profil recherché / Prérequis')),
                ('benefits', models.TextField(blank=True, verbose_name='Avantages')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('internship', 'Stage'), ('freelance', 'Freelance / Mission'), ('apprentice', 'Alternance / Apprentissage'), ('parttime', 'Temps partiel')], default='cdi', max_length=20, verbose_name='Type de contrat')),
                ('experience_level', models.CharField(choices=[('junior', 'Junior (0–2 ans)'), ('mid', 'Confirmé (2–5 ans)'), ('senior', 'Senior (5+ ans)'), ('lead', 'Lead / Manager'), ('no_require', 'Sans exigence')], default='no_require', max_length=20, verbose_name="Niveau d'expérience")),
                ('work_mode', models.CharField(choices=[('onsite', 'Présentiel'), ('remote', 'Télétravail'), ('hybrid', 'Hybride')], default='onsite', max_length=10, verbose_name='Mode de travail')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu de travail')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire minimum (FCFA ou autre)')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire maximum')),
                ('salary_is_public', models.BooleanField(default=True, verbose_name='Afficher le salaire publiquement')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Clôturée')], default='draft', max_length=15, verbose_name='Statut')),
                ('deadline', models.DateTimeField(verbose_name='Date limite de candidature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='companies.company', verbose_name='Entreprise')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL, verbose_name='Recruteur')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
    ]
