# Generated by Django 6.0.5 on 2026-05-31 14:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Nom de l'entreprise")),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mission', models.TextField(blank=True, verbose_name='Mission / Valeurs')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Page LinkedIn')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('sector', models.CharField(blank=True, max_length=150, verbose_name="Secteur d'activité")),
                ('size', models.CharField(blank=True, choices=[('micro', 'Micro (1–9 employés)'), ('small', 'Petite (10–49 employés)'), ('medium', 'Moyenne (50–249 employés)'), ('large', 'Grande (250–999 employés)'), ('enterprise', 'Très grande (1000+ employés)')], max_length=20, verbose_name='Taille')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Année de création')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('active', 'Active'), ('suspended', 'Suspendue')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.company', verbose_name='Entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement entreprise',
                'verbose_name_plural': 'Abonnements entreprises',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
